### ISSUE TITLE
help..

### ISSUE THREAD

**Issue by ghost** [AutoUOC/site#12]
i am banned on scratch.
I will get unbanned on friday.
https://autouoc.github.io/site/index.html < add this to the [Topic](https://scratch.mit.edu/discuss/topic/434082/)

**Comment by ghost** [comment]
Also, please make a repository called AutoUOC.github.io and give me access to edit these repositories cuz it's making me create forks.

**Comment by bremea** [comment]
Hi, we've added it to the topic. We're not giving anyone member permission unless they've created a few very helpful pulls, mostly to our api repo.

**Comment by ghost** [comment]
But... what does the API do? Anyways, can i only do changes to the site repository? I only know HTML & CSS, not those advanced programming launguages like Javascript & Phyton.
