### ISSUE TITLE
[Bug] Github pages doesn't work with node.js - we might need another host.

### ISSUE THREAD

**Issue by pufferfish101007** [AutoUOC/site#15]
**Describe the bug**
Basically, Github Pages only works for static sites, so we won't get a true or correct representation of how the site will really work - and the database stuff won't work either.

**To Reproduce**
1. Go to 'autouoc.github.io/site/'
This should route to the page that you see at 'autouoc.github.io/site/src/views/index.html'
2. But it doesn't. Instead you see the file at index.html, not in src/views/
3. See (here)[https://www.google.com/url?sa=t&source=web&rct=j&url=https://stackoverflow.com/questions/15718649/how-to-publish-a-website-made-by-node-js-to-github-pages&ved=2ahUKEwjn_66Tg7vrAhWBQxUIHQEdCJQQFjAAegQIChAB&usg=AOvVaw1h-dqT69YpwfNSzv6x2hm5] for proof that it doesn't work.

**Screenshots**
What it should look like at `autouoc.github.io/site`:
![Screenshot_2020-08-27-10-05-41](https://user-images.githubusercontent.com/50246616/91420647-e4ae2d00-e84c-11ea-84f7-a812d7be0454.png)
What it does look like:
![Screenshot_2020-08-27-10-07-10](https://user-images.githubusercontent.com/50246616/91420834-1a531600-e84d-11ea-824c-d23ff4ea6b61.png)

**Smartphone:**
 - Device: Samsung Galaxy S4 mini
 - OS: android 4.4.4
 - Browser Chrome (but mobile version, obviously)
 - Version: I don't know, and I don't think it matters. Sorry.

**Possible solution**
Seeing as I have a Glitch project, if people have Glitch accounts I can invite you to edit it, or we could just set up an automatic workflow that updates it when this repo's updated...
Or, we could use another hosting provider.

**Comment by ghost** [comment]
No, [the second one](https://autouoc.github.io/site/) is a design by me.
[The actual one](https://autouoc.github.io/site/src/views/index.html) is currently in another URL for testing.

**Comment by pufferfish101007** [comment]
I know - that's what I'm saying, we shouldn't need to have all the long urls - we should be able to use the routing. We need the routing so we can have a server for the database stuff. At the moment it doesn't matter, but in time it will.

**Comment by ghost** [comment]
Well then, i'm trying to add a redirect page.  Please rename index.html to TEMPORARY-index.html
And then, make a file called "index.html" with this:
https://justpaste.it/47x6l

**Comment by pufferfish101007** [comment]
I don't have write access to this repo, sorry. You can add it to your own
fork and make a pull request, if you want.

**Comment by bremea** [comment]
Their pull request was denied. I'll work on getting my own host setup that updates with GitHub and I'll post more here when I have it done.

**Comment by ghost** [comment]
> Their pull request was denied. I'll work on getting my own host setup that updates with GitHub and I'll post more here when I have it done.

Why don't you use the settings panel?
[(screenshot)](http://u.cubeupload.com/LankyBox01/XQIm97.png)
It's much easier, and **(most of it is)** free!
I found these, that are completely free:

AutoUOC.tk
AutoUOC.ml
AutoUOC.ga
AutoUOC.cf
AutoUOC.gq
AutoUOC.free
AutoUOC.ads
UOCbot.free
UOCbot.tk

**Comment by pufferfish101007** [comment]
@LankyBox01 It still won't work, because it's still hosted with Github.
@BreMea Great, thanks!

**Comment by ghost** [comment]
> @LankyBox01 It still won't work, because it's still hosted with Github.
>
It works, i tested it.

**Comment by bremea** [comment]
Okay, I'm setting up the host now.

For beta it's likely we'll snatch the subdomain https://autouoc.bremea.com/ (subdomain of my wip personal site). If I feel we should get https://autouoc.com/ then I'll be more than happy to pay.

@LankyBox01 This is being hosted with node. **This is not a static website.** Please do more research into node.js and express before contributing. We aren't using freenom because it looks highly unprofessional.

**Comment by ghost** [comment]
> Okay, I'm setting up the host now.
> 
> For beta it's likely we'll snatch the subdomain https://autouoc.bremea.com/ (subdomain of my wip personal site). If I feel we should get https://autouoc.com/ then I'll be more than happy to pay.
> 
> @LankyBox01 This is being hosted with node. **This is not a static website.** Please do more research into node.js and express before contributing. We aren't using freenom because it looks highly unprofessional.

FINE! I CAN GET YOU THE .COM DOMAIN!
Sorry for all caps, i am out of my mind.

I can register you the .com domain! For 1 price: invite me to be a collaborator.

**Comment by bremea** [comment]
> FINE! I CAN GET YOU THE .COM DOMAIN!
> Sorry for all caps, i am out of my mind.
> 
> I can register you the .com domain! For 1 price: invite me to be a collaborator.

I will be registering the domain since it's my website and I'm hosting it. Please do not buy the domain.

**Comment by pufferfish101007** [comment]
Ok, now it's sorted, I'l close this issue.
