### ISSUE TITLE
Index page used XHTML

### ISSUE THREAD

**Issue by ghost** [AutoUOC/site#16]
The Index page used XHTML, which is outdated.

Most of the content would stay the same.

**Comment by ghost** [comment]
The current index page is [this](https://autouoc.github.io/site/index.html)... oh wait! I just checked... no

**Comment by bremea** [comment]
Noted, I'll work on fixing this later.

**Comment by ghost** [comment]
LankyBox01's pull request updating the 404 page also made the 404 page use XHTML.

**Comment by LankyBox01** [comment]
> LankyBox01's pull request updating the 404 page also made the 404 page use XHTML.

should i repair it? Or.. i guess BreMea would do it :)

**Comment by ghost** [comment]
> LankyBox01's pull request updating the 404 page also made the 404 page use XHTML.

Touché
