### ISSUE TITLE
[Suggestion] Cookies.

### ISSUE THREAD

**Issue by ghost** [AutoUOC/site#18]
**Is your feature request related to a problem? Please describe.**
Not really, but it would be a good improvement to our site.

**Describe the solution you'd like**
We should add cookies! Lemme explain: These cookies would allow people to save their log-in (Local storage), and other cookies would allow us to see which people('s IP addresses) are on the site! And no, this isn't a privacy concern as long as we add a message at the bottom saying that we collect your data.

**Describe alternatives you've considered**
We could use the "Insights" tab in github, but that only counts how many have seen the github repositories, not the actual site.

**Additional context**
--

**Comment by bremea** [comment]
We're already working on cookies, along with the rest of the account features.

**Comment by ghost** [comment]
What kind of cookies? you know we can use google analytics.
