### ISSUE TITLE
> index.html is permanent.

### ISSUE THREAD

**Issue by ghost** [AutoUOC/site#20]
> index.html is permanent.

No, the index **i made**, because i wanna make a new index.html that would redirect to the **actual** one.

_Originally posted by @LankyBox01 in https://github.com/AutoUOC/site/pull/17#issuecomment-681906161_

**Comment by ghost** [comment]
https://github.com/AutoUOC/site/blob/master/index.html
This is the one i wanna rename.

I wanna make a new index.html that will redirect to https://autouoc.github.io/site/src/views/index.html

**Comment by bremea** [comment]
We don't need that index.html since express will be broadcasting the current one to whichever domain we choose.

**Comment by ghost** [comment]
> We don't need that index.html since express will be broadcasting the current one to whichever domain we choose.

Then what did you made this for > https://autouoc.github.io/site/src/views/index.html

**Comment by bremea** [comment]
That's the index.html... express will broadcast the views folder... this isn't a static website. Fixed with removal of both 404 and index files.
