### ISSUE TITLE
New 404

### ISSUE THREAD

**Issue by ghost** [AutoUOC/site#27]
I have made this new 404 thing for the website, which fits more nicely with the design!
https://pastebin.com/qwi97aq4

**Comment by ghost** [comment]
Also, can you please replace the dot after AutoUOC with an exclamation mark in the homepage?

**Comment by bremea** [comment]
I'll take a look in a second

**Comment by ghost** [comment]
> I'll take a look in a second

you done yet?

**Comment by bremea** [comment]
> Also, can you please replace the dot after AutoUOC with an exclamation mark in the homepage?
This was intentional.

> you done yet?
Please be patient.

**Comment by bremea** [comment]
Denied, since we don't need a report button and we have to focus on the main site first. If you want new features please make a pull request.
