### ISSUE TITLE
(About) page.

### ISSUE THREAD

**Issue by ghost** [AutoUOC/site#31]
I'm currently developing the About page. any ideas on what i should add?

**Comment by bremea** [comment]
I'll do this since I know of the relevant information of the project.

Please use issues for issue reporting only. Use the forum thread for discussion.

Please only let members create pages.

**Comment by ghost** [comment]
> I'll do this since I know of the relevant information of the project.
> 
> Please use issues for issue reporting only. Use the forum thread for discussion.
> 
> Please only let members create pages.

Well, i am banned on scratch until friday.

**Comment by bremea** [comment]
Due to irrelevant issues and pulls, getting banned on Scratch (!!), and just a general lack of understanding of this project, you've been blocked from contributing for 1 day. If you continue these actions it will be extended. Please stay on-topic.
